apiVersion: apps/v1
kind: Deployment
metadata:
  name: silverwin
  namespace: silverwin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silverwin
  template:
    metadata:
      labels:
        app: silverwin
    spec:
      containers:
        - name: silverwin
          image: matejci/silverwin:latest
          imagePullPolicy: Always
          env:
            - name: SECRET_KEY_BASE
              value: 5d38b8ade69fe20e180d21b72352841842c82ca2dfe55dad1562a5a901538f6c2f3b9d52c2e320e1f431996aa89f1cff9ad5b21658931c7ab72cbd7c8c0218f6
            - name: RAILS_ENV
              value: production
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: REDIS_URL
              value: redis://redis:6379/0
          ports:
            - containerPort: 3000
